name: Kernel Config - A13 5.10

permissions:
  contents: write # Allow writing to repository contents
  actions: write # Allows triggering actions

on:
  workflow_call:
    inputs:
      ksu_commit:
        required: false
        type: string
      feature_set:
        required: true
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernels-a13-5-10:
    name: "5.10.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        # Deprecated series (Android 13 - 5.10)
        - sub_level: "246"
          os_patch_level: "2026-01"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_commit: ${{ inputs.ksu_commit }}
      feature_set: ${{ inputs.feature_set }}
      build_bypass: ${{ inputs.build_bypass }}
